### ISSUE TITLE
Check to see if pythreejs will work in Vocareum's notebooks

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#18]
I'd like to use pthreejs for the 3D visualizations and animations, but it's sometimes a bit tricky to get functioning properly with Jupyter. I haven't used it with the classic notebook interface in a long time, so I'm not sure how it works with it now. We should verify that it can be installed in Vocareum and that it works.

**Comment by moorepants** [comment]
It seems that Jupyter is running under Python 3.5, so I did:

```
python3.5 -m pip install --user pythreejs
```

but because pythreejs (latest version) doesn't work with python 3.5 this happens:

```
ddd_v1_t_olvC_735068@runweb47427:/home/ddd_v1_t_olvC_735068$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 657, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 1034, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/mnt/voccontent/teacherlib/ddd_v1_t_olvC_735068/work/asn719011_4/asn719012_1/work/.local/lib/python3.5/site-packages/pythre
ejs/__init__.py", line 253
    'src': f'{_prefix()}/share/jupyter/labextensions/{npm_pkg_name}/',
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by moorepants** [comment]
I tried installing an older version of pythreejs that might work with Python 3.5:
```
python3.5 -m pip install --user "pythreejs<2.3"
```

But then:

```
ddd_v1_t_olvC_735068@runweb47427:/home/ddd_v1_t_olvC_735068$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
Installing /mnt/voccontent/teacherlib/ddd_v1_t_olvC_735068/work/asn719011_4/asn719012_1/work/.local/lib/python3.5/site-packages/pyt
hreejs/static -> jupyter-threejs
Symlinking: /usr/share/jupyter/nbextensions/jupyter-threejs -> /mnt/voccontent/teacherlib/ddd_v1_t_olvC_735068/work/asn719011_4/asn
719012_1/work/.local/lib/python3.5/site-packages/pythreejs/static
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 657, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 184, in install_nbextension
    os.symlink(path, full_dest)
PermissionError: [Errno 13] Permission denied: '/mnt/voccontent/teacherlib/ddd_v1_t_olvC_735068/work/asn719011_4/asn719012_1/work/.
local/lib/python3.5/site-packages/pythreejs/static' -> '/usr/share/jupyter/nbextensions/jupyter-threejs'
```
Can't write to directories I need to.

**Comment by moorepants** [comment]
This worked!
```
ddd_v1_t_olvC_735068@runweb47427:/home/ddd_v1_t_olvC_735068$ jupyter nbextension install --user --py --symlink pythreejs
Installing /mnt/voccontent/teacherlib/ddd_v1_t_olvC_735068/work/asn719011_4/asn719012_1/work/.local/lib/python3.5/site-packages/pyt
hreejs/static -> jupyter-threejs
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable pythreejs --user --py
```

**Comment by moorepants** [comment]
So everything was working in the teacher view. I then released the notebooks, update, and click "student view". I try running the notebook and pythreejs is not installed:
![image](https://user-images.githubusercontent.com/276007/151590808-947e4645-222e-471e-b342-e25e97eb6469.png)

**Comment by moorepants** [comment]
That was my error. Notice above the kernel is set to Python 3.7. If I change to Python 3.8, then the notebook runs and I get pythreejs output in the student view:
![image](https://user-images.githubusercontent.com/276007/151591489-b90e1429-eecc-4517-8878-cabd10c9b553.png)

**Comment by moorepants** [comment]
Vocareum reported that this package is now installed. We need to check whether it works.

**Comment by moorepants** [comment]
On April 1, Sarah wrote:

> Good morning Jason,
>
> I just received this from Vocareum: We have installed the requested pkgs and updated them to EU. The instructor should be ready to go.
>
> So you should be all set! Let me know if anything doesn’t work as expected.

I've tested Pythreejs in the teacher view (MB course, "Testing Q4 Packages" assignment"). It imports but no visualizations display. My guess is that they did not install the jupyter notebook extension. This also points out that they probably didn't try to run the example notebook I sent them to prove it works.

**Comment by moorepants** [comment]
This has been reported to teaching support on April 24.
